### ISSUE TITLE
Requesting example that works.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [RangerMauve/mutable-webtorrent#2]
Hi,

Looking to use mutable torrents to keep files for a program up to date across many peers.
If it's not too much trouble would you be able to show an example that works like this..

Master.js creates a magnet link and logs it out if not already exist.
Watches directory for changes, if any made, add the changes and publish a new version of the torrent?

Client.js given a magnet link will download it.
On next run it will check for any updates and download first.
When all downloads are finished and files are up to date I suspect there would some kind of event published?

Can the client have an opt-in re-seed to other peers?

Can the client checksum the files based on the current version of the torrent to check if any are incorrect?

Many thanks.

**Comment by RangerMauve** [comment]
Hey, that seems like a bit more than an example. 😅

I'd suggest hiring a Node developer and getting them to play around with the library.
